---
output:
  html_document:
    theme: cerulean
    highlight: tango
    code_folding: show
    toc: yes
    toc_float: yes
    number_sections: true
  pdf_document:
    number_sections: yes
geometry: margin = 1.2in
fontsize: 10pt
always_allow_html: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


knitr::knit_hooks$set(
   error = function(x, options) {
     paste('\n\n<div class="alert alert-danger">',
           gsub('##', '\n', gsub('^##\ Error', '**Error**', x)),
           '</div>', sep = '\n')
   },
   warning = function(x, options) {
     paste('\n\n<div class="alert alert-warning">',
           gsub('##', '\n', gsub('^##\ Warning:', '**Warning**', x)),
           '</div>', sep = '\n')
   },
   message = function(x, options) {
     paste('\n\n<div class="alert alert-info">',
           gsub('##', '\n', x),
           '</div>', sep = '\n')
   }
)
```


# Schedule Google Compute Engine via Cloud Scheduler

Google released Cloud Scheduler, which is a managed cron service that can perform tasks for other Google services. With that launch, Google also released a tutorial titled [Scheduling Instances with Cloud Scheduler](https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule), demonstrating how you can programmatically start and stop instances using Cloud Scheduler in conjunction with Cloud Functions. 

## Create PubSub Trigger

```{bash, eval=F}
gcloud pubsub topics create start-instance-event
gcloud pubsub topics create stop-instance-event
```


```{bash, eval=F}
git clone https://github.com/GoogleCloudPlatform/nodejs-docs-samples.git

cd nodejs-docs-samples/functions/scheduleinstance/
```

## Create the start and stop functions


```{bash, eval=F}
cd nodejs-docs-samples/functions/scheduleinstance/
gcloud functions deploy startInstancePubSub \
    --trigger-topic start-instance-event \
    --runtime nodejs6
```

```{bash, eval=F}
cd nodejs-docs-samples/functions/scheduleinstance/
gcloud functions deploy stopInstancePubSub \
    --trigger-topic stop-instance-event \
    --runtime nodejs6
```
Testing the function with the helper of encoded zone and instance name:

```{bash, eval=F}
echo '{"zone":"europe-west3-c", "instance":"cloudbreak"}' | base64
```

```{bash, eval=F}
gcloud functions call stopInstancePubSub \
    --data '{"data":"eyJ6b25lIjoiZXVyb3BlLXdlc3QzLWMiLCAiaW5zdGFuY2UiOiJjbG91ZGJyZWFrIn0K"}'
```

Check that the instance has a status of TERMINATED. It may take up to 30 seconds to finish shutting down.


```{bash, eval=F}
gcloud compute instances describe cloudbreak \
    --zone europe-west3-c \
    | grep status
```

## Set up the Cloud Scheduler jobs to call Cloud Pub/Sub


Create the start job.

```{bash, eval=F}
gcloud beta scheduler jobs create pubsub startup-workday-instance \
    --schedule '35 9 * * 1-7' \
    --topic start-instance-event \
    --message-body '{"zone":"europe-west3-c", "instance":"cloudbreak"}' \
    --time-zone 'Europe/Zurich'
```


Create the stop job.


```{bash, eval=F}
gcloud beta scheduler jobs create pubsub shutdown-workday-instance \
    --schedule '45 09 * * 1-7' \
    --topic stop-instance-event \
    --message-body '{"zone":"europe-west3-c", "instance":"cloudbreak"}' \
    --time-zone 'Europe/Zurich'
```

Verify the job works

```{bash, eval=F}
gcloud beta scheduler jobs run shutdown-workday-instance
```


