---
title: "Untitled"
output: ioslides_presentation
---


```{r setup, include=FALSE}
#Caching of all chunks
knitr::opts_chunk$set(cache=TRUE)
```
## R Markdown


```{r}
#remotes::install_github("JohnCoene/echarts4r") # github
#remotes::install_github("JohnCoene/echarts4r.suite")
```



## Slide with Bullets

```{r}
library(dplyr)
library(echarts4r)
library(echarts4r.assets)

e1 <- iris %>% 
  group_by(Species) %>% 
  e_charts(
    Sepal.Length,
    elementId = "chart"
  ) %>% 
  e_scatter(Petal.Length, Sepal.Width) %>% 
  e_datazoom(show = FALSE, y_index = 0) %>% 
  e_x_axis(min = 4) %>%  
  e_highlight(
    series_name = list("setosa", "versicolor", "virginica"), 
    btn = "high"
  ) %>% 
  e_downplay(
    series_name = list("setosa", "versicolor", "virginica"), 
    btn = "down"
  ) %>% 
  e_button(
    "high", "Highlight", 
    class = "btn btn-primary", 
    position = "bottom"
  ) %>% 
  e_button(
    "down", "Downplay", 
    class = "btn btn-default", 
    position = "bottom"
  ) %>% 
  e_legend(FALSE) %>% 
  e_title("Connect charts") %>% 
  e_tooltip(
    trigger = "item",
    axisPointer = list(
      type = "cross"
    )
  ) %>% 
  e_image_g(
    left = 50,
    top = 30,
    z = 999,
    style = list(
      image = "reference/figures/logo.png",
      width = 70,
      height = 75,
      opacity = .95
    )
  ) %>% 
  e_text_style(fontFamily = "Raleway")

e2 <- iris %>% 
  group_by(Species) %>%
  e_charts(Petal.Length) %>% 
  e_line(Sepal.Length) %>% 
  e_connect("chart") %>% 
  e_datazoom(y_index = 0) %>% 
  e_x_axis(min = 0) %>% 
  e_legend(
    bottom = 5,
    icons = ea_icons(
      c("warning", "signal", "photo")
    )
  ) %>% 
  e_tooltip(
    trigger = "item",
    axisPointer = list(
      type = "cross"
    )
  ) %>% 
  e_text_style(fontFamily = "Raleway")

e_arrange(e1, e2, rows = 1, cols = 2)
```
## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

