---
title: "Untitled"
output:
  html_document:
    theme: cerulean
    highlight: tango
    code_folding: hide
    toc: yes
    toc_float: false
---



#STRAVA

```{r}
a=1
```

#Load token

fdsafdd

fds
f
dsf
ds
f

ds
fa
d
f
ds
f
dsfd

# fdsfs

# Executive Summary

SOURCE: http://freerangestats.info/blog/2017/09/09/rmarkdown

# Purpose

This is basically just a demo of how to deal with a few issues with making R Markdown files comply with corporate styling - fonts, logo, heading sizes and colours, etc.  The [source code of the mini-project that builds this file is on GitHub](https://github.com/ellisp/rmarkdown-corporate-eg).  There is also an accompanying [blog post](http://ellisp.github.io/blog/2017/09/09/rmarkdown) on Peter's Stats Stuff.

The features include:

* logo in the top right of the document, and modify the title's width to allow for it
* heading styles and fonts in the html
* fonts and corporate colours used in the graphics
* document builds successfully even if the project is on a mapped network drive which usually causes problems with RStudio Server and Pandoc

# Analysis

## Data

