---
title: "admin"
output: html_document
---


```{r}
site_path = "/home/danny/00_blog/content/post"
folder<-"/home/danny/OneDrive/DataScience/11_GitHub_DannyJRa.github.io/"
filename<-list.files(folder, pattern = "BLOG.md",recursive = TRUE, full.names = TRUE)
filename
file.copy(filename, site_path, recursive = TRUE)

```


#TODO
https://www.r-bloggers.com/regular-expressions-every-r-programmer-should-know/
```{r}
site_path = "/home/danny/00_blog/static/img"
filename<-list.files(folder, pattern = "BLOG.png$|BLOG.jpg$|BLOG.gif$",recursive = TRUE, full.names = TRUE)
filename
files<-basename(filename)
files
file.copy(filename, site_path, recursive = TRUE)
# AND copy to img subfolder
file.copy(filename, "img/", recursive = TRUE)
#file.copy(filename, "/mnt/sshftps/floox/images", recursive = TRUE)
```

```{r}
site_path = "/home/danny/00_blog/static/img"
filename<-list.files(folder, pattern = "BLOG.jpg",recursive = TRUE, full.names = TRUE)
filename
file.copy(filename, site_path, recursive = TRUE)
```


```{r}
setwd("/home/danny/00_blog/")
#blogdown::serve_site()
blogdown::hugo_build()
```


```{bash}
cd $HOME/00_blog

git add -A
git commit -m "commit blog 73 draft"
git push
```
### List all html

```{r}

folder<-"/home/danny/OneDrive/DataScience/11_GitHub_DannyJRa.github.io/"
filename<-list.files(folder, pattern = "BLOG.html",recursive = TRUE, full.names = TRUE)
filename
```

```{r}

folder<-"/home/danny/OneDrive/DataScience/11_GitHub_DannyJRa.github.io/"
filename<-list.files(folder, pattern = "BLOG.html",recursive = TRUE, full.names = FALSE,include.dirs=F)
filename
files<-basename(filename)
# [1] "a.ext"

titles <- gsub("_", 
                      " ",
                      files, fixed = TRUE)
titles <- gsub("BLOG.html", 
                      "",
                      titles, fixed = TRUE)


folders<-dirname(filename)
# [1] "C:/some_dir"
library(tidyverse)
data=as.data.frame(files)

data<-data %>% 
  add_column(title=titles)  %>% 
  add_column(folders)  %>% 
  add_column(github_page_prefix="https://dannyjra.github.io") %>%
  add_column(github_page=paste0("https://dannyjra.github.io/",folders,"/",files)) %>%
  add_column(github_repo_prefix="https://github.com/DannyJRa/DannyJRa.github.io/tree/master/")

library(openxlsx)
write.xlsx(file = "links.xlsx",data)


```

```{r}



url <- gsub("/home/danny/OneDrive/DataScience/11_GitHub_DannyJRa.github.io", 
                      "https://dannyjra.github.io",
                      filename, fixed = TRUE)
url
write.csv(file = "links.csv",url)
```

```{r}



url <- gsub("/home/danny/OneDrive/DataScience/11_GitHub_DannyJRa.github.io", 
                      "",
                      filename, fixed = TRUE)

data<-strsplit(url, split="/", fixed = FALSE, perl = FALSE, useBytes = FALSE)



write.csv(file = "links.csv",url)
```