---
title: "admin"
output: html_document
---



```{r}
blog_path="/home/danny/OneDrive/DataScience/42_Website_dannyrasch/02_Blog-Airspace"
```


```{r}
site_path = paste0(blog_path,"/content/english/blog/")
folder<-"/home/danny/OneDrive/DataScience/41_DannyJRa.github.io"
filename<-list.files(folder, pattern = "BLOG.md",recursive = TRUE, full.names = TRUE)

#TEST
#filename=filename[1:2]

filename
```

## Copy blogs
```{r}
file.copy(filename, site_path, recursive = TRUE)
```


### Absolut path
```{r}
# it's better to use - or _ in file name instead of white space.
# press tab in link to refresh the rstudio preview
# need absoluate path because servr changed current working directory.
process_md <- function(md_path, site_path) {
  # assume asset folder has same name of rmd name
  file_name <- basename(md_path)
  asset_folder <- substr(file_name, 1, nchar(file_name) - 3)
  # change relative path of assets folder to absolute path
  # to deal with encoding, there are some internal functions. just assume utf 8 here.
  # input_lines <- rmarkdown:::read_lines_utf8(rmd_path, getOption("encoding"))
  input_lines <- readLines(md_path)
  
  #input_lines <- gsub(paste0('](img/'), 
  #                    paste0('](/img/'),
  #                    input_lines, fixed = TRUE)
  

  
  input_lines <- gsub(paste0('image: "img/'), 
                      paste0('image: images/blog/'),
                      input_lines, fixed = TRUE)
  
  input_lines <- gsub(paste0('BLOG.jpg"'), 
                      paste0('BLOG.jpg'),
                      input_lines, fixed = TRUE)
    
    input_lines <- gsub(paste0('BLOG.gif"'), 
                      paste0('BLOG.gif'),
                      input_lines, fixed = TRUE)
    input_lines <- gsub(paste0('BLOG.png"'), 
                      paste0('BLOG.png'),
                      input_lines, fixed = TRUE)
       

  input_lines <- gsub(paste0('src="img/'), 
                      paste0('src="/img/'),
                      input_lines, fixed = TRUE)
  
    input_lines <- gsub(paste0('(img/'), 
                      paste0('(/images/blog/'),
                      input_lines, fixed = TRUE)
  
  post_path <- file.path(site_path, "content","english", "blog", file_name)
  writeLines(input_lines, post_path)
  # copy asset folder to static/. also assume using / instead of \
 # asset_path <- file.path(dirname(md_path), asset_folder)
 # static_path <- file.path(site_path, "static")
  #file.copy(asset_path, static_path, recursive = TRUE)
}
```

```{r}
i=1
for(i in c(1:length(filename))) {
  process_md(md_path=filename[i],site_path=blog_path)
  print(i)
  }
```


#TODO
https://www.r-bloggers.com/regular-expressions-every-r-programmer-should-know/
```{r}
site_path = paste0(blog_path,"/static/images/blog")

filename<-list.files(folder, pattern = "BLOG.png$|BLOG.jpg$|BLOG.gif$",recursive = TRUE, full.names = TRUE)
filename
files<-basename(filename)
files
file.copy(filename, site_path, recursive = TRUE)
# AND copy to img subfolder
#file.copy(filename, "img/", recursive = TRUE)
#file.copy(filename, "/mnt/sshftps/floox/images", recursive = TRUE)
```






```{r,eval=F}
setwd("/home/danny/00_blog/")
#blogdown::serve_site()
blogdown::hugo_build()
```


```{bash}
cd $HOME/OneDrive/DataScience/42_Website_dannyrasch/02_Blog-Airspace

git add -A
git commit -m "commit blog 96"
git push
```









### List all html

```{r}

folder<-"/home/danny/OneDrive/DataScience/41_DannyJRa.github.io/"
filename<-list.files(folder, pattern = "BLOG.html",recursive = TRUE, full.names = TRUE)
filename
```

```{r}

folder<-"/home/danny/OneDrive/DataScience/41_DannyJRa.github.io/"
filename<-list.files(folder, pattern = "BLOG.html",recursive = TRUE, full.names = FALSE,include.dirs=F)
filename
files<-basename(filename)
# [1] "a.ext"

titles <- gsub("_", 
                      " ",
                      files, fixed = TRUE)
titles <- gsub("BLOG.html", 
                      "",
                      titles, fixed = TRUE)


folders<-dirname(filename)
# [1] "C:/some_dir"
library(tidyverse)
data=as.data.frame(files)

data<-data %>% 
  add_column(title=titles)  %>% 
  add_column(folders)  %>% 
  add_column(github_page_prefix="https://dannyjra.github.io") %>%
  add_column(github_page=paste0("https://dannyjra.github.io/",folders,"/",files)) %>%
  add_column(github_repo_prefix="https://github.com/DannyJRa/DannyJRa.github.io/tree/master/")

library(openxlsx)
write.xlsx(file = "links.xlsx",data)


```

# Write Links to csv

```{r}



url <- gsub("/home/danny/OneDrive/DataScience/42_Website_dannyrasch", 
                      "",
                      filename, fixed = TRUE)

data<-strsplit(url, split="/", fixed = FALSE, perl = FALSE, useBytes = FALSE)


write.csv(file = "links2.csv",url)
#write.csv(file = "links2.csv",data)
```