---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

devtools::install_github("coatless/ghapi3")
```{r}
library(gh)


my_repos <- gh("DannyJRa", type = "public")
vapply(my_repos, "[[", "", "name")
```

```{r}
#install.packages("jsonlite")
library(jsonlite)
#install.packages("httpuv")
library(httpuv)
#install.packages("httr")
library(httr)

# Can be github, linkedin etc depending on application
oauth_endpoints("github")

# Change based on what you 
myapp <- oauth_app(appname = "Test",
                   key = "90818e934fb522fc73e0",
                   secret = "5db5abbb6c24a1e47b41099e118cd399246c8a30")

# Get OAuth credentials
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)

# Use API
gtoken <- config(token = github_token)
req <- GET("https://api.github.com/users/DannyJRa/repos", gtoken)

req <- GET("https://api.github.com/repos/DannyJRa/HomeAssistant/stats/commit_activity", gtoken)

req <- GET("https://api.github.com/repos/DannyJRa/HomeAssistant/commits", gtoken)


# Take action on http error
stop_for_status(req)

# Extract content from a request
json1 = content(req)

# Convert to a data.frame
gitDF = jsonlite::fromJSON(jsonlite::toJSON(json1))

# Subset data.frame
gitDF[gitDF$full_name == "DannyJRa/HomeAssistant", "created_at"] 
```

```{r}
lf <- list.files(path = getwd(), pattern = "\\.Rmd$", full.names=TRUE,recursive = TRUE)
lf
```

