---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Source:

```{r}
```

```{r}
install.packages("tidyverse")
install.packages("data.table")
install.packages("gganimate")
devtools::install_github('thomasp85/gganimate')
#apt-get install cargo
install.packages("gifski")
```

```{r}

library(tidyverse)
library(data.table)
library(gganimate)
library(gifski)
# 1st pattern
n_points  <- 20
closeness <- 2*pi/n_points
speed     <- 2*pi/n_points
v_angles <- seq(0, 2*pi, length.out = n_points)

# 2nd pattern
n_points  <- 20
closeness <- 0
speed     <- 2*pi/n_points
v_angles <- seq(0, by=pi/2, length.out = n_points)

# 3rd pattern
n_points  <- 20
closeness <- 2*pi/n_points
speed     <- 2*pi/n_points
v_angles <- seq(0, 0, length.out = n_points)

# 4th pattern
n_points  <- 20
closeness <- pi/4
speed     <- 2*pi/n_points
v_angles <- seq(0, by=pi/4, length.out = n_points)

# This function creates a grid of vectors (coordinates and angle)
# using a initial vector of angles adding factor f each iteration
create_grid <- function(n, a, f) {
    lapply(seq_len(n), function (x) {a+f*(x-1)}) %>% 
    do.call("rbind", .) %>% 
    melt(varnames=c('x', 'y'), value.name="angle")
}

# This is what makes to spin the pins 
lapply(1:(n_points+1), function(x) {
  create_grid(n_points, 
              v_angles+(x-1)*speed,
              closeness)}) %>% 
  as.list(.) %>% 
  rbindlist(idcol="frame") -> df

# Plot pins using frame as transition time
ggplot(df) +
  geom_spoke(aes(x=x, y=y, angle = angle), radius = 1) +
  geom_point(aes(x+cos(angle), y+sin(angle)), size=4) +
  theme_void() + 
  coord_fixed() +
  transition_time(time=frame)

# Do you want to save it?
anim_save("choose_a_name.gif")
```

Show in New WindowClear OutputExpand/Collapse Output
Error: The png package is required to use gifski_renderer

```{r}
library(ggplot2)
library(gapminder)
library(gganimate)

ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')
```

