# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /home/danny/docker/volumes/mongodb/data/:/data/db
      - /home/danny/docker/volumes/mongodb/configdb/:/data/configdb
    ports: 
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
